kind: Pod
apiVersion: v1
metadata:
  name: numatestdp-nosocket
spec:
  containers:
  - name: testdpcontainer
    image: numatestdp-nosocket 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "./numa-test-device-plugin --logtostderr -v 10" ]
    volumeMounts:
    - mountPath: /var/lib/kubelet/device-plugins/ 
      name: devicesock 
      readOnly: false
  volumes:
  - name: devicesock 
    hostPath:
      path: /var/lib/kubelet/device-plugins/
